version: 2.1
orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  orb_test:
    jobs:
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: stitch-cli/cli@0.1.4
          publish-token-variable: $CIRCLECI_DEV_API_TOKEN
          validate: true
